services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Symplify\SymfonyStaticDumper\:
        resource: "../src"
        exclude:
            - "../src/Exception/*"

    Symplify\SmartFileSystem\Finder\FinderSanitizer: null

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: null
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['@Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']
